---
application:
  name: "serverlessbot"
  project: "Test"
  organization: "QoveryCommunity"
routers:
- name: "main-serverlessbot"
  routes:
  - application_name: "serverlessbot"
    paths:
    - "/*"
